camel:
  component:
    log:
      exchange-formatter: '#class:org.apache.camel.support.processor.DefaultExchangeFormatter'


  context:
    name: quarkus-camel-example-timer-log-spring
  main:
    duration-hit-exit-code: 15
gtml:
  kafka:
    #allow-manual-commit: true
    #autoOffsetReset: latest
    #autocommitenable: false
    #breakOnFirstError: false
    #brokers: localhost:9092
    #consumersCount: 1
    #errorTopic: test
    #groupId: TestGroupName
    #metadataMaxAgeMs: 5000
    topic: test
guice:
  modules: 'com.tbe.gtml.module.GtmlCoreModule '
kafka:
  allow-manual-commit: true
  auto-commit-enable: false
  auto-offset-reset: latest
  break-on-first-error: false
  brokers: localhost:9092
  consumers-count: 1
  error-topic: test
  group-id: TestGroupName
  metadata-max-age-ms: 5000
  topic: test
quarkus:
  arc:
    remove-unused-beans: false
  banner:
    enabled: false
  log:
    category:
      "com.tbe.gtml":
            level: INFO
    console:
      color: false
      format: '%d{HH:mm:ss} %-5p [%c{2.}] (%t) %s%e%n'
      level: INFO
    file:
      enable: true
      format: '%d{HH:mm:ss} %-5p [%c{2.}] (%t) %s%e%n'
      level: INFO
      path: c:/logs/trace.log
    level: INFO
timer:
  period: 5000
